- создает миграции для всех таблиц в базе данных
htmlacademy-yii/1247385-task-force-2 pull request #10
Opened 2023-01-14 16:00 UTC by sigmarius

2023-01-16 22:49 UTC, VikingBO requested changes
Немного вопросов и замечаний

2023-01-16 22:49 UTC, VikingBO commented on config/web.php
> +//    'controllerMap' => [
этот участок можно удалить, в интерфейсе он нам не понадобится

2023-01-16 22:49 UTC, VikingBO commented on config/web.php
> +            'enablePrettyUrl' => false,
а почему решила отключить?

2023-01-16 22:49 UTC, VikingBO commented on assets/AppAsset.php
> +//        'yii\bootstrap5\BootstrapAsset'
разве шаблон не работает с бутсрапом?

2023-01-16 22:49 UTC, VikingBO commented on controllers/TasksController.php
> +use Yii;
подскажи зачем ты тут подключаешь столько классов, из них используется в файле вроде не больше двух

2023-01-16 22:49 UTC, VikingBO commented on fixtures/TasksFixture.php
> +    public $modelClass = 'app\models\Tasks';
тут кстати можно вместо прописывания адреса вручную сделать это используя сам класс, это выглядит так: `Tasks::class`   
В этом параметре передаётся путь до класса учитывая его namespace.

2023-01-16 22:49 UTC, VikingBO commented on web/view-task.html
> +                    <a class="link link--nav">Новое</a>
здесь можно было вообще ничего не трогать, это же шаблон или макет, то есть заготовка по которой мы уже делаем свою вёрстку в проекте, а в проекте мы сами html файлы не используем )))

2023-01-17 04:12 UTC, sigmarius commented on config/web.php
> +            'enablePrettyUrl' => false,
Мне больше нравился первый вариант, но в задании в разделе Проверка было сказано так, вот и пришлось выключить( - 

> Перейдите по адресу /index.php?r=tasks. Должна открыться страница со списком заданий. Задания отсортированы от новых к старым.

2023-01-17 04:22 UTC, sigmarius commented on assets/AppAsset.php
> +//        'yii\bootstrap5\BootstrapAsset'
Там в шаблоне в правом блоке с фильтром съезжает верстка при включенном бутстрапе - колонка с фильтром меньше стала, а до этого хедер еще отъезжал, я поправила где-то в стилях. А потом стала разбираться почему так, и заметила что бутстрап переопределяет стили шаблона. Нужно было или разбираться какие стили и править их, или выключить бутстрап) Я посмотрела в исходниках верстки - там подключался в стилях только style.css, и поэтому отключила бутстрап

2023-01-17 04:23 UTC, sigmarius commented on controllers/TasksController.php
> +use Yii;
Удалила неиспользуемые. Это я подглядела у SiteController, и скопировала тоже на всякий случай)

2023-01-17 04:27 UTC, sigmarius commented on config/web.php
> +//    'controllerMap' => [
Убрала закомментированный код. Хотела просто спросить - по материалам в п.5.11 "Генерация тестовых данных" конфигурация для фикстур определяется именно в web.php, но у меня так ничего не работало( Пришлось описывать конфигурацию в console.php, и там уже все нормально стало работать. Это неточность в описании, или я что-то не так сделала?

2023-01-17 04:36 UTC, sigmarius commented on fixtures/TasksFixture.php
> +    public $modelClass = 'app\models\Tasks';
Исправила, и перегенерила данные на всякий, вдруг как-то неправильно поняла.
Это просто потрясающе! Спасибо)

2023-01-17 04:41 UTC, sigmarius commented on web/view-task.html
> +                    <a class="link link--nav">Новое</a>
Здесь я ничего и  не делала, просто в уведомлениях было сообщение, что в проекте некорректная верстка, и я на всякий случай ее обновила
![image](https://user-images.githubusercontent.com/57371471/212811440-dbe39a28-4130-4b3e-a450-35076d63a2f4.png)

2023-01-17 04:42 UTC, sigmarius commented on config/web.php
> +//    'controllerMap' => [
вот тут было такое описание
![image](https://user-images.githubusercontent.com/57371471/212811654-8a55348e-1e0d-4043-a631-0fcd0531d381.png)

2023-01-17 04:44 UTC, sigmarius commented
Исправлены ошибки

2023-01-17 08:07 UTC, VikingBO reviewed
Всё отлично

2023-01-17 08:07 UTC, VikingBO commented on config/web.php
> +            'enablePrettyUrl' => false,
Ладно пока оставим, если что всегда можем поменять

2023-01-17 08:07 UTC, VikingBO commented on config/web.php
> +//    'controllerMap' => [
Да, скорее всего неверно просто указали файл конфига, логично что настройка должна быть в `console.php` так как с фикстурами мы работаем через консоль.

2023-01-17 08:07 UTC, VikingBO commented on web/view-task.html
> +                    <a class="link link--nav">Новое</a>
А точно, упустил этот момент, тогда всё супер )))

2023-01-17 08:07 UTC, VikingBO commented on assets/AppAsset.php
> +//        'yii\bootstrap5\BootstrapAsset'
Хорошо, нам это не принципиально, так что отключила и норм )))

2023-01-17 08:08 UTC, VikingBO approved these changes

2023-01-17 08:08 UTC, merged