- создана модель TasksSearch для поиска заданий по критериям из формы
htmlacademy-yii/1247385-task-force-2 pull request #11
Opened 2023-01-27 17:40 UTC by sigmarius

- создана модель TasksSearch для поиска заданий по критериям из формы
- создана форма
- реализована фильтрация заданий в соответствии с выбранными в форме условиями

2023-02-01 00:12 UTC, VikingBO requested changes
Ну мне всё очень нравится, ты реально прям вникаешь в процесс, это здорово.
Посмотри вопросы или заметки что я оставил, ну и пиши что бы обсудить если надо.

2023-02-01 00:12 UTC, VikingBO commented on fixtures/templates/tasks.php
> +    'worker_id' => $faker->numberBetween(0, 5),
А 0 в каких случаях понадобится?

2023-02-01 00:12 UTC, VikingBO commented on models/TasksSearch.php
> +    public function scenarios()
насколько я помню для отключения достаточно переопределить метод `rules()`, сценарии можно использовать для более детальной проработки модели, если брать те же `rules()` то для отдельных правил можно указывать конкретное название сценария к которому он будет применяться или наоборот к которому он не должен применяться.

2023-02-01 00:12 UTC, VikingBO commented on models/TasksSearch.php
> +        $now->modify("-$this->hoursPeriod hours");
очень плохая практика использовать двойные кавычки для  конкатенации данных, в частности для обработки в строке переменных, с версии 8.2 вроде такой способ уже не доступен к использованию.

2023-02-01 00:12 UTC, VikingBO commented on models/TasksSearch.php
> +                return !empty($categories) ? array_map(fn ($category) => (int) $category, $categories) : '';
тут ты видимо вторым вариантом хотела возвращать пустой массив?

2023-02-01 00:12 UTC, VikingBO commented on models/TasksSearch.php
> +        return Model::scenarios();
метод `scenarios()` не является статическим, как подсказывает  IDE, поэтому он не может быть вызван статически.

2023-02-01 00:12 UTC, VikingBO commented on models/TasksSearch.php
> +            ->joinWith('category')
а вот эти joins мы зачем добавляем?

2023-02-01 00:12 UTC, VikingBO commented on controllers/TasksController.php
> +        $categories = ArrayHelper::map($categories, 'id', 'name');
а вот тут могу подсказать ещё один способ получения нужного массива:
```
Categories::find()->select('name')->indexBy('id')->asArray()->all();
```
Этот запрос тоже вернёт массив имён, и индексом этих имён будет идентификатор категории.

2023-02-01 16:45 UTC, sigmarius commented on fixtures/templates/tasks.php
> +    'worker_id' => $faker->numberBetween(0, 5),
0 это у меня в случаях, когда нет исполнителя. В БД у меня worker_id - INT NOT NULL сделан, и в миграции тоже.
Вот и перегенерировала данные, не подумала об этом с самого начала

2023-02-01 16:52 UTC, sigmarius commented on models/TasksSearch.php
> +    public function scenarios()
Это я взяла из примера в документации
![image](https://user-images.githubusercontent.com/57371471/216108493-f237f156-1b9e-4e4f-8354-57fb288f2e68.png)

2023-02-01 16:56 UTC, sigmarius commented on models/TasksSearch.php
> +        $now->modify("-$this->hoursPeriod hours");
Исправила на обычную конкатенацию

2023-02-01 17:03 UTC, sigmarius commented on models/TasksSearch.php
> +                return !empty($categories) ? array_map(fn ($category) => (int) $category, $categories) : '';
Здесь у меня валилась ошибка, если категории не были выбраны по view, не помогло даже то, что я вроде как отключила передачу значений через 'unselect' => null. И у меня все заработало только с таким костыльком(
![image](https://user-images.githubusercontent.com/57371471/216110185-e6913bed-3c11-4b67-8fd7-6c41bc4000be.png)

2023-02-01 17:04 UTC, sigmarius commented on models/TasksSearch.php
> +        return Model::scenarios();
Тут я тоже ориентировалась на пример из документации
![image](https://user-images.githubusercontent.com/57371471/216111626-bfa54ccd-0170-4e4f-be36-816aaafdff85.png)

2023-02-01 17:11 UTC, sigmarius commented on models/TasksSearch.php
> +            ->joinWith('category')
Это я почитала в учебнике про ленивую и жадную загрузку связанных моделей - https://up.htmlacademy.ru/yii/2/module/5/item/9.
Посмотрела в дебагере, и поняла, что жадная лучше - с этими джойнами в дебагере выполняется 11 запросов к БД, а без них - 31

2023-02-01 17:22 UTC, sigmarius commented on controllers/TasksController.php
> +        $categories = ArrayHelper::map($categories, 'id', 'name');
Не получилось у меня, и никак не могу понять, почему?... Вроде бы пишу также - 
![image](https://user-images.githubusercontent.com/57371471/216116406-19d99070-f6a7-42bc-b4a1-3e6de5d9f16e.png)

А это результат от var_dump
![image](https://user-images.githubusercontent.com/57371471/216116582-1c2ae196-a9ed-4ce7-b9e8-32d42bf08199.png)

2023-02-01 17:25 UTC, sigmarius commented
Исправила что смогла

2023-02-05 19:39 UTC, VikingBO commented on fixtures/templates/tasks.php
> +    'worker_id' => $faker->numberBetween(0, 5),
надо будет переделать, может к следующему заданию, миграцию поправить и сделать чуть посложнее логику в шаблоне, потому как идентификатор 0 тоже идентификатор, например в массивах же у нас первый числовой ключ `0`

2023-02-06 10:02 UTC, VikingBO commented on controllers/TasksController.php
> +        $categories = ArrayHelper::map($categories, 'id', 'name');
Да, это я немного перепутал записи, не нужно ни asArray ни all, вот так будет работать   
```php
Categories::find()->select('name')->indexBy('id')->orderBy(['id' => SORT_ASC])->column()
```

2023-02-27 00:26 UTC, VikingBO approved these changes

2023-02-27 00:26 UTC, merged